---

- hosts: relays
  vars:
    tor_ContactInfo: "{{ tor_ContactInfo }}"
tor_signingkeylifetime_days: 90
tor_nickname: "{{ ansible_hostname }}"
tor_ports:
    - { orport: 443, dirport: 444}
    - { orport: 444, dirport: 445}
    - { orport: 9000, dirport: 9001}
    - { orport: 9100, dirport: 9101}
  roles:
   - nusenu.relayor
